name: Release

# Release manually until release-gem supports something other than rake-release.
# rake-release is incompatible with GitHub Action workflows that run on tag.
# https://github.com/rubygems/release-gem/issues/3
# on:
#   push:
#     tags:
#       - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@v1
